application: go-widget
version: 0-0-6-devel
runtime: go
api_version: 1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: "7d"

- url: /
  script: _go_app
  login: optional

- url: /leaderboard
  script: _go_app
  login: optional

- url: /hook/.*
  script: _go_app
  login: optional

- url: /widget/show/.*
  script: _go_app
  login: optional

- url: /task/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
  login: required

builtins:
- datastore_admin: on
- deferred: on
